### ISSUE TITLE
概念错误

### ISSUE THREAD

**Issue by SleepyRiceYang** [KarryRen/SCU-CS-Class-Materials#1]
4.2 什么是端口？
端口应该是指各个IO接口寄存器的IO地址

**Comment by KarryRen** [comment]
来信收悉，会进行更改。
感谢支持❤️


On Jun 17, 2023, at 11:40, Rice Yang ***@***.***> wrote:

﻿

4.2 什么是端口？
端口应该是指各个IO接口寄存器的IO地址

**Comment by SleepyRiceYang** [comment]
感谢学长！
