### ISSUE TITLE
为仓库构建 Issue 模板

### ISSUE THREAD

**Issue by KarryRen** [KarryRen/SCU-CS-Class-Materials#19]
参考电子科大的内容构建 [Issue 模板](https://github.com/Xovee/uestc-course/issues/new/choose) 方便大家做出贡献。

**Comment by novelyear** [comment]
见[PR](https://github.com/KarryRen/SCU-CS-Class-Materials/pull/31)

**Comment by KarryRen** [comment]
完美，最近时间太紧，一直没有时间做。感谢贡献~
