### ISSUE TITLE
数据结构复习笔记中一处拼写

### ISSUE THREAD

**Issue by Uokaa007** [KarryRen/SCU-CS-Class-Materials#2]

**Comment by KarryRen** [comment]
感谢您对本项目的关注，我们会对该处拼写进行检查与修正！

祝好~

发件人: ***@***.***>
发送时间: 2023年10月31日 10:18
收件人: ***@***.***>
抄送: ***@***.***>
主题: Re: [KarryRen/SCU-CS-Class-Materials] 数据结构复习笔记中一处拼写 (Issue #2)


Closed #2<https://github.com/KarryRen/SCU-CS-Class-Materials/issues/2> as completed.

―
