### ISSUE TITLE
CONTRIBUTION.md是空的

### ISSUE THREAD

**Issue by Y0oMu** [KarryRen/SCU-CS-Class-Materials#21]
CONTRIBUTION.md是空的

**Comment by KarryRen** [comment]
感谢您的 Issue。正如此 [Issue](https://github.com/KarryRen/SCU-CS-Class-Materials/issues/14) 所说，我们正准备构建贡献手册。目前手册还在编写阶段~

如果您想加入到我们的项目中，建议您现在暂时参考[**此手册**](https://github.com/Xovee/uestc-course/blob/main/assets/%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97.md)进行内容贡献，我们目前开发的手册也是参考此模板。

希望能够给您带来帮助，如有疑问还可以继续交流~

**Comment by KarryRen** [comment]
###  @Y0oMu 我们已经完善了 Contribution.md，您可以查看。

本 Issue 完成修改，进行关闭
