### ISSUE TITLE
绘制项目 LOGO

### ISSUE THREAD

**Issue by KarryRen** [KarryRen/SCU-CS-Class-Materials#36]
如果大家参考其他高校的相似类型的 Repo。可以发现：在 README.md 的开头，有一个项目 LOGO，比如[电子科大的项目](https://github.com/Xovee/uestc-course)。有没有人可以帮我们设计一个类似的 LOGO 呢？

**Comment by jeanhua** [comment]
![课程资料分享平台](https://github.com/user-attachments/assets/9e4e8b34-4880-43bc-b505-38b45e5afe06)

**Comment by jeanhua** [comment]
![课程资料分享平台](https://github.com/user-attachments/assets/e284e8d0-3836-4dbd-8369-989ec2073354)

**Comment by jeanhua** [comment]
![课程资料分享平台2](https://github.com/user-attachments/assets/3518af72-78af-4edd-9ab1-08fd01f50a2a)

**Comment by KarryRen** [comment]
感谢您的参与，针对该 Logo 目前我有一个修改建议，目前我们的资料分享是只有计算机学院的，所以在课程资料分享平台前可以加上“计算机学院”。另外，个人感觉第一张要比第二张更好一些。希望您能稍作修改后再次提交～

**Comment by jeanhua** [comment]
![课程资料分享平台2](https://github.com/user-attachments/assets/b3b4075f-f7a2-4903-8231-e7a2db3d1bcc)

**Comment by KarryRen** [comment]
可以的！感谢您的贡献，我稍后会将 Logo 放入 README 中，并将您放入贡献者名单中。此 ISSUE 可以关闭。

**Comment by jeanhua** [comment]
贡献者名单里面已经有我了😂



---原始邮件---
发件人: "Kai ***@***.***&gt;
发送时间: 2024年9月7日(周六) 上午10:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [KarryRen/SCU-CS-Class-Materials] 绘制项目 LOGO (Issue #36)




 
可以的！感谢您的贡献，我稍后会将 Logo 放入 README 中，并将您放入贡献者名单中。此 ISSUE 可以关闭。
