### ISSUE TITLE
可以在保留部分公共课程的情况下，clone本项目构建SCU网络空间安全学院的资料库么？

### ISSUE THREAD

**Issue by Y0oMu** [KarryRen/SCU-CS-Class-Materials#37]
例如大学物理（理工）等课程
会按照原方式注明作者及出处

**Comment by KarryRen** [comment]
### 感谢您的询问

首先，我们团队十分感谢您询问我们有关版权的问题，也很感谢您能参考我们的工作，搭建相关的内容 ！

其次，我发现您已经 Fork 了我们的仓库，并如我们理解的一样保留了原始的文件。但是，**我们认为这可能并不是最好的解决方案**，原因有如下两点：
- 您保留的相关资料是完全相同的，如果直接按照资料文件进行保留，难免会造成信息冗余和空间浪费
- 在进行每次更新的时候，很难保证我们仓库中相关创作者被引入到您的仓库中，造成版权疑惑

因此，我们建议您**采用 README + 链接的方式**，引用我们的内容，也即：
- 您现在在每个学期中已经保留了 README 文件
- 如果需要引用我们仓库中的公共课程资料，可以在 README 文件的相关课程下，提供我们仓库中相关参考资料的引用链接，索引到我们仓库中

这样能解决上述两点关键问题，同时还能给网络空间安全学院的同学们提供较高质量、清晰的课程资料。

以上是我们目前的想法，如果没有问题，您可以对仓库内容进行修改，如果有任何疑问都可以在本 Isuue 中进行交流~

**Comment by Y0oMu** [comment]
好的，非常感谢，您提出的建议非常好。在Readme中已经提供了每个对应的继承自 SCU-CS-Class-Materials 课程仓库的记录。非常感谢计算机学院的同学们。
