### ISSUE TITLE
如何单独下载单个文件

### ISSUE THREAD

**Issue by KarryRen** [KarryRen/SCU-CS-Class-Materials#9]

**Comment by Orderheart** [comment]
1. 进入某一单个文档的界面：
<img width="975" alt="84082af0bf859c6e8f8abe16e4c6bd33" src="https://github.com/KarryRen/SCU-CS-Class-Materials/assets/114977087/34740be9-d878-4f7e-b390-f33c68a70a6b">
2. 点击“download raw file”，即可完成下载
<img width="981" alt="e9cc6367dd85558ce09224fa3b20b596" src="https://github.com/KarryRen/SCU-CS-Class-Materials/assets/114977087/37dd7cf3-ccca-4d94-9b68-7652ca11a0a6">
<img width="272" alt="4cc2a483e05ef743ab6a06561a4694fc" src="https://github.com/KarryRen/SCU-CS-Class-Materials/assets/114977087/ed191d35-47bb-430c-96db-fdbdcd2faf28">
